In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name": ["Aman", "Saurav", "Karan", "Shubham","Abhishek", None, "Sameer"],
    "Age": [22, 23, None, 22, 25,24, 26],
    "Marks": [85, None, 88, 90, 56,72, None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
})

In [3]:
df.shape

(7, 4)

In [4]:
df.dtypes

Name           str
Age        float64
Marks      float64
Subject        str
dtype: object

In [5]:
df.describe()

             Age      Marks
count   6.000000   5.000000
mean   23.666667  78.200000
std     1.632993  14.254824
min    22.000000  56.000000
25%    22.250000  72.000000
50%    23.500000  85.000000
75%    24.750000  88.000000
max    26.000000  90.000000

In [6]:
#selection
df_view=df[["Name","Marks"]]
df_view

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN

In [7]:
#Filtering
df[df["Marks"]>80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

In [8]:
#Complex filtering
df[(df["Age"]>22) & (df["Marks"]>80)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

In [9]:
#Aggregation
df["Subject"].value_counts()

Subject
Math         3
Physics      2
Chemistry    2
Name: count, dtype: int64

In [10]:
df_sorted=df.sort_values(by="Marks", ascending=False)
df_sorted

       Name   Age  Marks    Subject
3   Shubham  22.0   90.0  Chemistry
2     Karan   NaN   88.0       Math
0      Aman  22.0   85.0       Math
5       NaN  24.0   72.0    Physics
4  Abhishek  25.0   56.0       Math
1    Saurav  23.0    NaN    Physics
6    Sameer  26.0    NaN  Chemistry

In [11]:
df.nlargest(2,"Marks")

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

In [12]:
df.nsmallest(1,"Marks")

       Name   Age  Marks Subject
4  Abhishek  25.0   56.0    Math

In [13]:
df.isnull().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

In [14]:
df[df["Marks"].isnull()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

In [15]:
cleaned_df=df.dropna()

In [16]:
print("Original Shape: ", df.shape)
print("Cleaned Shape: ", cleaned_df.shape)

Original Shape:  (7, 4)
Cleaned Shape:  (3, 4)