In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame({
    "Name":["Aditi","Rohit", "Sneha","Karan",None ,"Alice","Meera","Arjun","Priya",None],
    "Department":["IT","Sales","HR","Sales","Sales", "IT", "Sales", "HR", "IT","HR"],
    "Role": ["Data Analyst", "HR Executive", "Accountant", "Software Engineer",
             "SEO Specialist", "Sales Manager", "ML Engineer",
             "Financial Analyst", "Recruiter", "Content Manager"],
    "Experience": [2, 3, 5, 4, 1, 6, 3, 2, 4, 5],
    "Salary": [450000, 400000, 600000, 750000, 350000,
               800000, 720000, 500000, 420000, 650000],
    "Score": [78, np.nan, 88, 91, np.nan, 89, 93, 81, np.nan, 85]
})

In [ ]:
df.groupby("Department")["Salary"].mean()
#print(avg)

Department
HR       583333.333333
IT       556666.666667
Sales    555000.000000
Name: Salary, dtype: float64

In [ ]:
df.groupby("Role")["Score"].mean()
#print(avg_per)

Role
Accountant           88.0
Content Manager      85.0
Data Analyst         78.0
Financial Analyst    81.0
HR Executive          NaN
ML Engineer          93.0
Recruiter             NaN
SEO Specialist        NaN
Sales Manager        89.0
Software Engineer    91.0
Name: Score, dtype: float64

In [ ]:
df.groupby("Department")["Score"].count()

Department
HR       3
IT       2
Sales    2
Name: Score, dtype: int64

In [ ]:
df.groupby("Department").size()

Department
HR       3
IT       3
Sales    4
dtype: int64

In [ ]:
df.groupby("Department")["Salary"].agg("mean","max","min","count")

Department
HR       583333.333333
IT       556666.666667
Sales    555000.000000
Name: Salary, dtype: float64

In [ ]:
df.groupby("Role")["Score"].agg("mean","max","min","count")

Role
Accountant           88.0
Content Manager      85.0
Data Analyst         78.0
Financial Analyst    81.0
HR Executive          NaN
ML Engineer          93.0
Recruiter             NaN
SEO Specialist        NaN
Sales Manager        89.0
Software Engineer    91.0
Name: Score, dtype: float64

In [ ]:
df.groupby(["Department","Role"])["Salary"].mean()

Department  Role
HR          Accountant           600000.0
            Content Manager      650000.0
            Financial Analyst    500000.0
IT          Data Analyst         450000.0
            Recruiter            420000.0
            Sales Manager        800000.0
Sales       HR Executive         400000.0
            ML Engineer          720000.0
            SEO Specialist       350000.0
            Software Engineer    750000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby(["Department","Experience"])["Score"].mean()

Department  Experience
HR          2             81.0
            5             86.5
IT          2             78.0
            4              NaN
            6             89.0
Sales       1              NaN
            3             93.0
            4             91.0
Name: Score, dtype: float64