In [1]:
import numpy as np
import pandas as pd

Series in pandas

In [2]:
s=pd.Series([10,20,30,40])

In [3]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
s=pd.Series([10,20,30], index=["a","b","c"])

In [5]:
print(s)

a    10
b    20
c    30
dtype: int64

In [6]:
print(s["a"])

10

In [7]:
print(s.iloc[0])

10

Series from Dictionary

In [8]:
data={"Math": 90, "Physics": 85, "Chemistry": 88}

In [9]:
marks=pd.Series(data)

In [10]:
print(data)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}

In [11]:
print(marks)

Math         90
Physics      85
Chemistry    88
dtype: int64

DataFrame in pandas

In [12]:
data={
    "Name":["Aman","Krish","Karan"],
    "Age":[22,23,21],
    "Marks":[85,90,88]
}

In [13]:
print(data)

{'Name': ['Aman', 'Krish', 'Karan'], 'Age': [22, 23, 21], 'Marks': [85, 90, 88]}

In [14]:
type(data)

dict

In [15]:
marks=pd.DataFrame(data)

In [16]:
print(marks)

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88

In [17]:
marks=pd.DataFrame(data,index=["Student1","Student2","Student3"])

In [18]:
print(marks)

           Name  Age  Marks
Student1   Aman   22     85
Student2  Krish   23     90
Student3  Karan   21     88

In [19]:
marks.set_index("Name",inplace=True) #if we are setting inplace=True it means we are changing the original object itself.

In [20]:
print(marks)

       Age  Marks
Name
Aman    22     85
Krish   23     90
Karan   21     88

In [21]:
df=pd.DataFrame({
    "Name": ["Aman","Saurav","Karan"],
    "Age": [22,23,21],
    "Marks": [85,90,88]
})

In [22]:
print(df)

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [23]:
df.head()

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [24]:
df.tail()

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90
2   Karan   21     88

In [25]:
df=pd.DataFrame({
    "Name": ["Aman","Saurav","Karan","Shubham","Abishek","Sameer"],
    "Age": [22,23,21,22,25,26],
    "Marks": [85,90,88,90,56,70]
})

In [26]:
df.head(2)

     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90

In [27]:
df.tail(3)

      Name  Age  Marks
3  Shubham   22     90
4  Abishek   25     56
5   Sameer   26     70

In [28]:
df.shape

(6, 3)

In [29]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [31]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   23.166667  79.833333
std     1.940790  13.891244
min    21.000000  56.000000
25%    22.000000  73.750000
50%    22.500000  86.500000
75%    24.500000  89.500000
max    26.000000  90.000000

In [32]:
df["Name"]

0       Aman
1     Saurav
2      Karan
3    Shubham
4    Abishek
5     Sameer
Name: Name, dtype: str

In [33]:
df[["Name","Marks"]]

      Name  Marks
0     Aman     85
1   Saurav     90
2    Karan     88
3  Shubham     90
4  Abishek     56
5   Sameer     70

Filtering in Pandas

In [34]:
df[df["Marks"]>85]

      Name  Age  Marks
1   Saurav   23     90
2    Karan   21     88
3  Shubham   22     90

In [35]:
df[(df["Age"]>21) & (df["Marks"]>85)]

      Name  Age  Marks
1   Saurav   23     90
3  Shubham   22     90

Sorting + Value Count

In [36]:
df.sort_values("Marks")

      Name  Age  Marks
4  Abishek   25     56
5   Sameer   26     70
0     Aman   22     85
2    Karan   21     88
3  Shubham   22     90
1   Saurav   23     90

In [37]:
df.sort_values("Marks",ascending=False)

      Name  Age  Marks
1   Saurav   23     90
3  Shubham   22     90
2    Karan   21     88
0     Aman   22     85
5   Sameer   26     70
4  Abishek   25     56

In [38]:
df["Age"].value_counts()

Age
22    2
23    1
21    1
25    1
26    1
Name: count, dtype: int64

Handling Missing Values

In [39]:
#updating the dataset with null values
df = pd.DataFrame({
    "Name": ["Aman", "Saurav", "Karan", "Shubham", None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 26],
    "Marks": [85, None, 88, 90, 56, None]
})

In [40]:
df.isnull() #checking the missing values

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False   True

In [41]:
df.isnull().sum() #counting the missing values

Name     1
Age      1
Marks    2
dtype: int64

In [42]:
df.dropna() #dropping the missing values

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0

In [43]:
print(df)

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4      NaN  25.0   56.0
5   Sameer  26.0    NaN

GroupBy in Pandas

In [44]:
data={
    "Name" : ["Aman","Saurav","Karan","Shubham","Abhishek", None, "Sameer"],
    "Age" : [22,23,None, 22, 25, 24, 26],
    "Marks" : [85, None, 88, 90, 56, 72, None],
    "Subject": ["Math", "Physics","Math","Chemistry","Math","Physics","Chemistry"]
}

In [45]:
df=pd.DataFrame(data)

In [46]:
#basic groupby
df.groupby('Subject')["Marks"].mean() #mean marks per subject . by default they are

Subject
Chemistry    90.000000
Math         76.333333
Physics      72.000000
Name: Marks, dtype: float64

In [47]:
df.groupby("Subject")["Name"].count() #count students per subject

Subject
Chemistry    2
Math         3
Physics      1
Name: Name, dtype: int64

In [48]:
#Multiple aggregations
df.groupby("Subject")["Marks"].agg(["mean","min","max"])

                mean   min   max
Subject
Chemistry  90.000000  90.0  90.0
Math       76.333333  56.0  88.0
Physics    72.000000  72.0  72.0

In [49]:
df.groupby("Subject")["Marks"].agg(["mean","min","max","count"])

                mean   min   max  count
Subject
Chemistry  90.000000  90.0  90.0      1
Math       76.333333  56.0  88.0      3
Physics    72.000000  72.0  72.0      1

In [50]:
#group by multiple columns
df.groupby(["Subject","Age"])["Marks"].mean()

Subject    Age
Chemistry  22.0    90.0
           26.0     NaN
Math       22.0    85.0
           25.0    56.0
Physics    23.0     NaN
           24.0    72.0
Name: Marks, dtype: float64